apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: polishbot-ingress
  namespace: polishbot
  labels:
    service: polishbot
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:950310456124:certificate/17461193-8078-4cff-b7c2-94a63e95d763 
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-port: traffic-port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "2"
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/load-balancer-name: polishbot-alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/security-groups: sg-0af4da31b0ec9df7b
    alb.ingress.kubernetes.io/subnets: subnet-0abc4d099c6a9087e,subnet-03bcd1d0eb06f33d0,subnet-0487c303076c54b1b
    alb.ingress.kubernetes.io/actions.ssl-redirect: '{"Type": "redirect", "RedirectConfig": {"Protocol": "HTTPS", "Port": "443", "StatusCode": "HTTP_301"}}'
    alb.ingress.kubernetes.io/tags: own:primary=nagaprabu.nagaswaran@freshworks.com,own:team=centralsre,svc:name=polishbot
    alb.ingress.kubernetes.io/target-type: ip
    kubernetes.io/ingress.class: alb
    kubernetes.io/rewrite-target: /
spec:
  ingressClassName: alb
  rules:
  - host: felp-polishbot.centralsre.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: polishbot-service
            # namespace: polishbot
            port:
              number: 80